### ISSUE TITLE
error when importing mpathic 

### ISSUE THREAD

**Issue by jurquiza** [jbkinney/mavenn#5]
I am running using Docker, with Dockerfile 

FROM ubuntu:18.04
RUN apt-get upgrade
RUN apt-get update
RUN apt-get install -y gcc
RUN apt-get install -y libblas-dev liblapack-dev
RUN apt-get install -y gfortran
RUN apt-get install -y python-pip
RUN apt-get install -y git
RUN pip install ipython numpy
RUN pip install mpathic==0.5

also tried mpathic==0.6 both generate the same error 

I get the following error:

>>> import mpathic as mpa
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/mpathic/__init__.py", line 64, in <module>
    from mpathic.src.simulate_sort import SimulateSort
  File "/usr/local/lib/python2.7/dist-packages/mpathic/src/simulate_sort.py", line 11, in <module>
    from mpathic.src import Models
  File "/usr/local/lib/python2.7/dist-packages/mpathic/src/Models.py", line 20, in <module>
    from mpathic.src import fast
  File "__init__.pxd", line 872, in init fast
ValueError: numpy.ufunc has the wrong size, try recompiling. Expected 192, got 216

**Comment by atareen** [comment]
Hi jurquiza,

from your error message, it may be that you have multiple copies of numpy installed or one of your packages (e.g. scipy) is complied against a newer version of numpy than the one you have on your machine, e.g. see https://github.com/scipy/scipy/issues/3448 or https://stackoverflow.com/questions/53904157/numpy-ufunc-has-the-wrong-size-try-recompiling-even-with-the-latest-pandas-and

If you could read into these issues and check your package versions, that would be great. I just did a fresh install of mpathic on google colab and it imported okay for me: 

<img width="1339" alt="Screenshot 2019-06-09 22 06 11" src="https://user-images.githubusercontent.com/6977064/59168473-dec31380-8b03-11e9-8bc6-7eac58700f42.png">

It may also be that because I have not updated the mpathic dependency package versions in the setup.py in quite a while, that may be causing this issue with docker. If you could first look into the links I posted (and the links inside them) and see if you can resolve the issue, that would be great. Alternatively, I could do another release in a few days with updated package dependency versions and that would likely solve the issue.

-Ammar

**Comment by jurquiza** [comment]
Progress 

User needs to install BLAS a lapack through apt-get install 

The user has to pin down numpy==1.14.2 if the user does not pin down to this version then there are problems with the dependencies installed (I didn't went very deep into this issue)

Then run the container in bash mode, 
run 
apt-get install python-tk 

then commit the new docker image. This is because python tk requires input from the user for installation

**Comment by atareen** [comment]
Great! you can use numpy 1.14.2 for as a temporary solution. I will update the mpathic dependencies soon with the next release. Please report back if you encounter any other issues.

Best,
-Ammar
