### ISSUE TITLE
The version attribute

### ISSUE THREAD

**Issue by mahdikooshkbaghi** [jbkinney/mavenn#9]
Hi,
Seems `MAVENN` has no `__version__` attribute yet.

**Comment by atareen** [comment]
Hi Mahdi, 

I'll add this attribute in the next release, in the meantime, you can run  `pip list | grep mavenn` to get the PyPI version.

**Comment by atareen** [comment]
Hi again Mahdi, I think it makes sense to use `pip list | grep mavenn` to get the version, since the PyPI version is intended to be the official package. Mavenn source pulled from github may differ from the official version (e.g. if there is additional development), which may cause confusion. Thanks.
